const huastecaAltaZone = [
    "PÁNUCO", "PUEBLO VIEJO", "TAMPICO ALTO", "EL HIGO", "TEMPOAL", "OZULUAMA DE MASCAREÑA"
];

const huastecaBajaZone = [
    "TANTOYUCA", "CHICONAMEL", "CHALMA", "PLATÓN SÁNCHEZ", "CHONTLA", "CITLALTÉPETL", "TAMIL",
    "TANTIMA", "CHINANPA DE GOROSTIZA", "TAMIAHUA", "NARANJOS AMATLÁN", "TANCOCO", "ITXCATEPEC",
    "CERRO AZUL", "TEPETZINTLA", "CHICONTEPEC", "BENITO JUÁREZ", "IXHUATLÁN DE MADERO", "TLACHICHILCO",
    "TEXCATEPEC", "ZONTECOMATLÁN DE LÓPEZ Y FUENTES", "ILAMATLÁN", "ZACUALPAN", "HUAYACOCOTLA",
    "ÁLAMO TEMAPACHE", "TUXPAN"
];

const totonacaZone = [
    "CASTILLO DE TEAYO", "TIHUATÁN", "CAZONES DE HERRERA", "POZA RICA DE HIDALGO", "COATZINTLA",
    "PAPANTLA", "GUTIÉRREZ ZAMORA", "TECOLUTLA", "ESPINAL", "COYUTLA", "COAHUITLÁN", "FILOMENO MATA",
    "MECATLÁN", "CHUMATLÁN", "COXQUIHUI", "ZOZOCOLCO DE HIDALGO"
];

const nautlaZone = [
    "SAN RAFAEL", "MARTÍNEZ DE LA TORRE", "TLAPACOYAN", "NAUTLA", "VEGA DE ALATORRE", "MISANTLA",
    "ATZALAN", "YECUATLA", "COLIPA", "JUCHIQUE DE FERRER"
];

const capitalZone = [
    "JALACINGO", "ALTOTONGA", "TENOCHTITLÁN", "LANDERO Y COSS", "CHICONQUIACO", "ALTO LUCERO DE GUTIÉREZ BARRIOS",
    "TEPETLÁN", "ACATLÁN", "MIAHUATLÁN", "TONAYÁN", "TATATILA", "TLACOLULAN", "COACOATZINTLA", "NAOLINCO",
    "JILOTEPEC", "BANDERILLA", "TLALNELHUAYOCAN", "XALAPA", "CAPITAL", "CAPITAL DEL ESTADO", "PEROTE", "AYAGUALULCO",
    "IXHUACÁN DE LOS REYES", "XICO", "COSAUTLÁN DE CARVAJAL", "COATEPEC", "TLALTETELA", "JALCOMULCO", "APAZAPAN",
    "EMILIANO ZAPATA", "ACTOPAN", "URSULO GALVÁN"
];

const lasMontañasZone = [
    "AQUILA", "MALTRATA", "ACULTZINGO", "SOLEDAD ATZOMPA", "XOXOCOTLA", "TLAQUILPA", "ASTACINGA", "TEHULPANGO", "MIXTA DE ALTAMIRANO",
    "ZONGOLICA", "TEZONAPA", "OMEALCA", "CUITLÁHUAC", "CARRILLO PUERTO", "PASO DEL MACHO", "CAMARÓN DE TEJADA", "ZENTLA",
    "COMAPA", "TLACOTEPEC DE MEJÍA", "TENANPA", "TOTUTLA", "SOCHIAPA", "HUATUSCO", "COSCOMATEPEC", "ALPATLÁHUAC", "CALCAHUALCO",
    "TOMATLÁN", "IXHUATLÁN DEL CAFÉ", "TEPATLAXCO", "AMATLÁN DE LOS REYES", "CÓRDOBA", "FORTÍN", "IXTACZOQUITLÁN", "NARANJAL",
    "TILAPAN", "TEQUILA", "NOGALES", "COETZALA", "YANGA", "ATOYAC", "ZENTLA", "CHOCAMÁN", "ATZACAN", "ORIZABA", "MAGDALENA", "CUICHAPA",
    "LOS REYES", "TEXHUACÁN", "MENDOZA", "HUILOAPAN DE CUAUHTÉMOC", "RAFAEL DELGADO", "RIO BLANCO", "SAN ANDRÉS TENEJAPAN"
];

const sotaventoZone = [
    "PUENTE NACIONAL", "PASO DE OVEJAS", "SOLEDAD  DE DOBLADO", "COTAXTLA", "TLALIXCOYAN", "MEDELLÍN", "BOCA DE RIO", "VERACRUZ",
    "LA ANTIGUA", "MANLIO FABIO ALTAMIRANO", "JAMAPA"
];

const papaloapanZone = [
    "TIERRA BLANCA", "TRES VALLES", "OTATITLÁN", "TLACOJALPAN", "TUXTILLA", "CHACALTIANGUIS", "JOSÉ AZUETA", "PLAYA VICENTE",
    "SANTIAGO SOCHIAPAN", "JUAN RODRÍGUEZ CLARA", "ISLA", "TLACOTALPAN", "SALTABARRANCA", "LERDO DE TEJADA", "ANGEL R. CABADA",
    "ALVARADO", "IGNACIO DE LA LLAVE", "ACULA", "AMATITLÁN", "CARLOS A. CARRILLO", "IXMATLAHUACAN", "COSOAMALOAPAN DE CARPIO"
];

const losTuxtlaZone = [
    "SANTIAGO TUXTLA", "SAN ANDRÉS TUXTLA", "HUEYAPAN DE OCAMPO", "CATEMACO", "MECAYAPAN"
];

const olmecaZone = [
    "SAN JUAN EVANGELISTA", "ACAYUCAN", "SOTEAPAN", "TETAHUICAPAN DE JUÁREZ", "PAJAPAN", "COATZACOALCOS", "AGUA DULCE", "LAS CHOAPAS",
    "UXPANAPA", "JESÚS CARRANZA", "SAYULA DE ALEMÁN", "OLUTA", "SOCONUSCO", "MECAYUAPAN", "CHINAMECA", "COSOLEACAQUE", "ZARAGOZA",
    "NACHITAL DE LAZARO CARDENAZ DEL RIO", "IXHUATLÁN DEL SURESTE", "MOLOACÁN", "MINATITLÁN", "HIDALGOTITLÁN", "JÁLTIPAN", "TEXISTEPEC",
    "OTEAPAN"
];

const dataZone = [{ zone: "HUASTECA ALTA", municipalities: huastecaAltaZone, zoneId: 1 }, { zone: "HUASTECA BAJA", municipalities: huastecaBajaZone, zoneId:2 },
{ zone: "TOTONACA", municipalities: totonacaZone, zoneId: 3 }, { zone: "NAUTLA", municipalities: nautlaZone, zoneId: 4 }, { zone: "CAPITAL", municipalities: capitalZone, zoneId: 5 },
{ zone: "LAS MONTANAS", municipalities: lasMontañasZone, zoneId: 6 }, { zone: "SOTAVENTO", municipalities: sotaventoZone, zoneId: 7 },
{ zone: "PAPALOAPAN", municipalities: papaloapanZone, zoneId: 8 }, { zone: "LOS TUXTLA", municipalities: losTuxtlaZone, zoneId: 9 }, { zone: "OLMECA", municipalities: olmecaZone, zoneId: 10 }];
